name: trevor-web
recipe: pantheon
config:
  framework: wordpress
  xdebug: true
  site: trevor-web
  id: b60ba3a2-cd76-4e32-9990-a5b89450ec59
  edge: false
proxy:
  appserver_nginx:
    - trevor-web.lndo.site
  mailhog:
    - trevor-mailhog.lndo.site
  phpmyadmin:
    - trevor-phpmyadmin.lndo.site
  node:
    - trevor-node.lndo.site:3000
events:
  pre-rebuild:
    - appserver: rm -rf source/plugin/lib
    - appserver: rm -rf source/theme/lib
    - node: rm -rf node_modules
  pre-push:
    - node: sh /app/scripts/pre-push-node.sh
  post-push:
    - node: sh /app/scripts/post-push-node.sh
services:
  node:
    type: node:12
    port: 3000
    build_as_root:
      - apt-get update -y && apt-get install -y zlib1g-dev fontforge ruby ruby-dev
      - mkdir -p /tmp/fc
      - cd /tmp/fc && git clone https://github.com/bramstein/sfnt2woff-zopfli.git sfnt2woff-zopfli && cd sfnt2woff-zopfli && make && mv sfnt2woff-zopfli /usr/local/bin/sfnt2woff
      - cd /tmp/fc && git clone --recursive https://github.com/google/woff2.git && cd woff2 && make clean all && mv woff2_compress /usr/local/bin/ && mv woff2_decompress /usr/local/bin/
      - gem install fontcustom
      - rm -rf /tmp/fc
    build:
      - npm install
      - /app/lando/fontcustom/entrypoint.sh all
    command: npm start
    app_mount: false
    overrides:
      volumes:
        - ./source:/app:delegated
      environment:
        CI: 'true' # required to keep webpack-dev-server running
        WDS_SOCKET_HOST: trevor-node.lndo.site
        NODE_OPTIONS: --max-old-space-size=4096 # fixes FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin:5.0
    hosts:
      - database
  appserver:
    build:
      - composer --working-dir=source/plugin install
      - composer --working-dir=source/theme install
    overrides:
      environment:
        MEDIA_DEV_PATH_PREFIX: 'http://trevor-node.lndo.site/'
        XDEBUG_CONFIG: ''
      volumes:
        - ./source/plugin:/app/web/wp-content/plugins/trevor
        - ./source/theme:/app/web/wp-content/themes/trevor
        - ./source/schema.xml:/app/web/wp-content/uploads/solr-for-wordpress-on-pantheon/schema.xml
        - ./logs:/app/web/wp-content/uploads/private/trevor/logs:delegated
        - ./source/lando/appserver/xdebug.ini:/usr/local/etc/php/conf.d/zzzz-xdebug.ini
tooling:
  composer: disabled
  composer-plugin:
    service: appserver
    cmd: /usr/local/bin/composer --working-dir=source/plugin
  composer-theme:
    service: appserver
    cmd: /usr/local/bin/composer --working-dir=source/theme
  npm:
    service: node
    cmd: npm
  ifonts:
    service: node
    cmd: /app/lando/fontcustom/entrypoint.sh
