<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitTrevorWPTheme
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TrevorWP\\Theme\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TrevorWP\\Theme\\' => 
        array (
            0 => __DIR__ . '/../..' . '/inc',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitTrevorWPTheme::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitTrevorWPTheme::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
